#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:-"amd64"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/..

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=mischavandenburg

if echo $TAG | grep -q dirty; then
  TAG=dev
fi

IMAGE=${REPO}/kbench:${TAG}
# original command:
# docker build -t ${IMAGE} -f package/Dockerfile .

# build for amd (running on macbook):
docker build --platform linux/amd64 -t ${IMAGE} -f package/Dockerfile .
echo Built ${IMAGE}

